#pragma once

#include <asio.hpp>
#include <cstdint>
#include <memory>

namespace cudp {
namespace network {

class CUDP;

/**
 * @brief Abstract interface for a connection object that implements
 * different logics of reliability and congestion control. The class
 * serves as a template for the CUDP multiplexer to handle the connections
 */
class ConnectionHandler : public std::enable_shared_from_this<ConnectionHandler> {
public:
  /**
   * @brief Enables safe destruction through the abstract interface
   */
  virtual ~ConnectionHandler() = default;

  /**
   * @brief Receives one message from the associated connection
   * @param p_data Message bytes, valid only for the duration of this call
   * @param p_size Number of valid message bytes
   */
  virtual void onMessage(const uint8_t *p_data, uint32_t p_size) = 0;

  /**
   * @brief Sends one message generated by the user
   * @param p_data Message bytes, valid only for the duration of this call
   * @param p_size Number of valid message bytes
   */
  virtual void sendMessage(const uint8_t *p_data, uint32_t p_size) = 0;

  /**
   * @brief Initializes the handler with the multiplexer instance
   * @param p_remote Remote endpoint associated with the handler
   * @param p_cudp CUDP multiplexer instance needed by the handler
   */
  void init(const asio::ip::udp::endpoint &p_remote, std::weak_ptr<CUDP> p_cudp) {
    m_remote_endpoint = p_remote;
    m_cudp_mux        = p_cudp;
  }

protected:
  // CUDP instance that is used by the Connection Handler to send back messages
  // and interact with the remote part. A weak ptr is used to avoid circular
  // dependencies
  std::weak_ptr<CUDP> m_cudp_mux;

  // Remote endpoint associated with the current connection handler
  asio::ip::udp::endpoint m_remote_endpoint;
};

} // namespace network
} // namespace cudp
